### ISSUE TITLE
Nested Buildable in Collection?

### ISSUE THREAD

**Issue by thisiscam** [google/FreeBuilder#249] opened 2017-05-30 00:50 UTC
Hi all,

I was just wondering if nested buildable in collection is(or will be) implemented? Or is there something I am missing that prohibits such pattern?

**Comment by chrisalice** [comment] 2017-05-30 10:16
This is a duplicate of issue #8. Currently FreeBuilder is in maintenance-only mode, so this is unlikely to be implemented in the short term, I'm afraid 😞

**Closed by chrisalice** 2017-05-30 10:16 UTC
