### ISSUE TITLE
Support setFoo(Foo.Builder) for nested buildable types

### ISSUE THREAD

**Issue by fluentfuture** [google/FreeBuilder#45] opened 2015-03-11 04:24 UTC

**Comment by cjp39** [comment] 2015-03-11 14:13
I _think_ this is a duplicate of #45, which is fixed but has only just been released as part of 1.0-rc6.

**Comment by cjp39** [comment] 2015-03-13 10:18
This should be in google3 now. Could you try to reproduce the issue?

**Comment by fluentfuture** [comment] 2015-03-14 15:28
Just synced. Still can't use setFoo(Builder) or addFoo(Builder).

**Comment by cjp39** [comment] 2015-03-14 16:01
Could you attach a repro?

**Comment by cjp39** [comment] 2016-01-19 23:23
Closing as no repro provided. Sorry!

**Closed by cjp39** 2016-01-19 23:23 UTC
